const express = require("express");
const cors = require("cors");
const cookieParser = require("cookie-parser");
const patentRoutes = require("./routes/patent.routes");
const authRoutes = require("./routes/auth.routes");
const app = express();
app.use(cors());
app.use(express.json());
app.use(cookieParser());
app.use("/api", patentRoutes);
app.use("/auth",authRoutes);
module.exports = app;