const express = require("express");
const patentController = require("../controllers/patent.controller");
const router = express.Router();
const authMiddleware = require("../middleware/auth");
router.get("/patents",  patentController.getAllPatents);
router.get("/patents/analysis/summary", patentController.getPatentAnalysis);
router.get("/patents/:id", patentController.getPatentById);
router.post("/patents", patentController.addPatent);
router.put("/patents/:id", patentController.updatePatent);
router.patch("/patents/:id", patentController.updatePatent);
router.delete("/patents/:id", patentController.deletePatent);
module.exports = router;
