-- AlterTable
ALTER TABLE `patent` MODIFY `status` ENUM('APPLIED', 'PUBLISHED', 'GRANTED') NOT NULL DEFAULT 'PUBLISHED',
    MODIFY `publicationDate` DATETIME(3) NULL,
    MODIFY `publicationNo` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `user` ADD COLUMN `designation` ENUM('STUDENT', 'ASSISTANT_PROFESSOR', 'ASSOCIATE_PROFESSOR', 'PROFESSOR') NULL;
